// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}},
{"name":"WfayPlugin","status":true,"description":"Wfay42's test plugin","parameters":{}}
];
